name: hombuddy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  provider: ^6.1.1
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0
  firebase_storage: ^11.6.6
  image_picker: ^1.0.7
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places: ^0.3.0
  flutter_image_compress: ^2.1.0
  location: ^5.0.3
  geocoding: ^2.2.0
  table_calendar: ^3.1.1
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  page_transition: ^2.1.0

  path: any
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  flutter_local_notifications: ^17.1.2
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/Hombuddy.png
    - lib/assets/images/add.png
    - lib/assets/images/backarrow.png
    - lib/assets/images/bookings-removebg-preview.png
    - lib/assets/images/car_maintenance-removebg-preview.png
    - lib/assets/images/carwash-removebg-preview.png
    - lib/assets/images/cleaning-removebg-preview.png
    - lib/assets/images/Homb.png
    - lib/assets/images/Hombuddy.png
    - lib/assets/images/home-removebg-preview.png
    - lib/assets/images/house_cleaning-removebg-preview.png
    - lib/assets/images/messages-removebg-preview.png
    - lib/assets/images/minus.png
    - lib/assets/images/more-removebg-preview.png
    - lib/assets/images/pc_repair-removebg-preview.png
    - lib/assets/images/plumbing-removebg-preview.png
    - lib/assets/images/Screenshot 2023-01-25 231636.png
    - lib/assets/images/search-removebg-preview.png
    - lib/assets/images/star empty.png
    - lib/assets/images/star.png
    - lib/assets/images/wellness-removebg-preview.png
    - lib/assets/images/example1.jpg
    - lib/assets/images/example2.jpeg
    - lib/assets/images/example3.jpg
    - lib/assets/images/Advert1.jpg
    - lib/assets/images/Advert2.jpg
    - lib/assets/images/Advert3.jpg
    - lib/assets/images/dd-removebg-preview.png
    - lib/assets/images/Reward.jpg
    - lib/assets/images/PCUpgrade.png
    - lib/assets/images/PCReformat.png
    - lib/assets/images/HardwareUpgrade.png
    - lib/assets/images/CompleteCarWash.png
    - lib/assets/images/BodyWash.png
    - lib/assets/images/EngineWash.png
    - lib/assets/images/UnderChassisCleaning.png
    - lib/assets/images/VacuumCleaning.png
    - lib/assets/images/ExteriorDetailing.png
    - lib/assets/images/InteriorDetailing.png
    - lib/assets/images/CompleteHomeClean.png
    - lib/assets/images/BathroomCleaning.png
    - lib/assets/images/FridgeCleaning.png
    - lib/assets/images/KitchenCleaning.png
    - lib/assets/images/OvenCleaning.png
    - lib/assets/images/SofaCleaning.png
    - lib/assets/images/FloorClean.png
    - lib/assets/images/CarpetCleaning.png
    - lib/assets/images/OilChange.png
    - lib/assets/images/TireRotation.png
    - lib/assets/images/BreakInspection.png
    - lib/assets/images/AirFilter.png
    - lib/assets/images/SparkPlug.png
    - lib/assets/images/GeneralPlumbing.png
    - lib/assets/images/KitchenFix.png
    - lib/assets/images/BathroomFix.png
    - lib/assets/images/BathroomFittingsInstall.png
    - lib/assets/images/KitchenFittingsRepair.png
    - lib/assets/images/DecloggingWork.png
    - lib/assets/images/WaterLineInstallation.png
    - lib/assets/images/WaterLineRepair.png
    - lib/assets/images/WaterMeterInstallation.png
    - lib/assets/images/GeneralPlumbing.png
    - lib/assets/images/FaceMassage.png
    - lib/assets/images/BodyMassage.png
    - lib/assets/images/FullService.png
    - lib/assets/images/FullBody.png
    - lib/assets/images/Glutathione.png
    - lib/assets/images/FootSpa.png
    - lib/assets/images/ACRepair-removebg-preview.png
    - lib/assets/images/LaptopRepair-removebg-preview.png
    - lib/assets/images/OvenRepair-removebg-preview.png
    - lib/assets/images/RefrigeratorRepair-removebg-preview.png
    - lib/assets/images/TVRepair-removebg-preview.png
    - lib/assets/images/WashingMachineRepair-removebg-preview.png
    - lib/assets/images/BathroomKitchen-removebg-preview.png
    - lib/assets/images/FullHomeClean-removebg-preview.png
    - lib/assets/images/PestControl-removebg-preview.png
    - lib/assets/images/SofaCarpetClean-removebg-preview.png
    - lib/assets/images/Carpenter-removebg-preview.png
    - lib/assets/images/Electrician-removebg-preview.png
    - lib/assets/images/Plumbing1-removebg-preview.png
    - lib/assets/images/FurnitureAssembly-removebg-preview.png
    - lib/assets/images/HairStudio-removebg-preview.png
    - lib/assets/images/LaserReduction-removebg-preview.png
    - lib/assets/images/MakeupStudio-removebg-preview.png
    - lib/assets/images/NailStudio-removebg-preview.png
    - lib/assets/images/Spa-removebg-preview.png
    - lib/assets/images/WomenSalon-removebg-preview.png
    - lib/assets/images/ExteriorClean-removebg-preview.png
    - lib/assets/images/InteriorClean-removebg-preview.png
    - lib/assets/images/MenSalon-removebg-preview.png
    - lib/assets/images/MassageMen-removebg-preview.png
    - lib/assets/images/HomePaint-removebg-preview.png
    - lib/assets/images/PictureToBeUploaded.png
    - lib/assets/images/Advv1.jpg
    - lib/assets/images/HombuddyBlack.png
    - lib/assets/images/HombuddyBlue.jpg
    - lib/assets/images/HombuddyBlueFull.jpg
    - lib/assets/images/UserSign.jpg
    - lib/assets/images/ExpertSign.jpg
    - lib/assets/images/HombuddyLogin.jpg
    - lib/assets/images/BookExample.jpg
    - lib/assets/images/SmallLogoBlue.jpg
    - lib/assets/images/ProfileExamplee.jpg
    - lib/assets/images/Refer.jpg
    - lib/assets/images/InstallUninstall1.jpg
    - lib/assets/images/RepairGas1.jpg
    - lib/assets/images/Service1.jpg
    - lib/assets/images/PowerJetACServiceSplit.jpg
    - lib/assets/images/FoamPowerJetACServiceSplit.jpg
    - lib/assets/images/PowerJetACServiceWindow.jpg
    - lib/assets/images/FoamPowerJetACServiceWindow.jpg
    - lib/assets/images/AntiRust.jpg
    - lib/assets/images/ACRepairSplitWindow.jpg
    - lib/assets/images/GasLeakFix.jpg
    - lib/assets/images/AirconInstall.jpg
    - lib/assets/images/AirconUninstall.jpg
    - lib/assets/images/AdAircon.jpg
    - lib/assets/images/ProfileIcon.jpg
    - lib/assets/images/MessagesIcon.jpg
    - lib/assets/images/HBIcon.jpg
    - lib/assets/images/PaymentIcon.jpg
    - lib/assets/images/ActivityIcon.jpg
    - lib/assets/images/Hombbu.jpg
    - lib/assets/images/ManageMyWallet.jpg
    - lib/assets/images/ManageLinkedBank.jpg
    - lib/assets/images/ManageMyRewards.jpg
    - lib/assets/images/SavedLocations.jpg
    - lib/assets/images/BookingHistory.jpg
    - lib/assets/images/AboutUs.jpg
    - lib/assets/images/TermsAndConditions.jpg
    - lib/assets/images/Logout.jpg
    - lib/assets/images/ChatWith.jpg
    - lib/assets/images/MyJobs.jpg
    - lib/assets/images/SidebySide.jpg
    - lib/assets/images/SingleDoor.jpg
    - lib/assets/images/DoubleDoor.jpg
    - lib/assets/images/RefAd.jpg
    - lib/assets/images/UninstallWashing.jpg
    - lib/assets/images/InstallWashing.jpg
    - lib/assets/images/RepairWashing.jpg
    - lib/assets/images/WashingMachineUninstall.jpg
    - lib/assets/images/WashingMachineInstall.jpg
    - lib/assets/images/SemiAutomatic.jpg
    - lib/assets/images/Frontload.jpg
    - lib/assets/images/Topload.jpg
    - lib/assets/images/MicrowaveRepair.jpg
    - lib/assets/images/AirCoolerAd.jpg
    - lib/assets/images/WashingMachineAd.jpg
    - lib/assets/images/MicrowaveAd.jpg
    - lib/assets/images/Nothing.jpg
    - lib/assets/images/Advv.jpg
    - lib/assets/images/MaayongAdlawHom.png
    - lib/assets/images/Pinn.png
    - lib/assets/images/HomeCleaning.png
    - lib/assets/images/RepairMaintenance.png
    - lib/assets/images/HomePaint.png
    - lib/assets/images/Wellness.png
    - lib/assets/images/Massage.png
    - lib/assets/images/FresherAirAd.png
    - lib/assets/images/RepairMaintenanceAd.png
    - lib/assets/images/AsLowAsAd.png
    - lib/assets/images/PlumbingAd.png
    - lib/assets/images/15offAd.png
    - lib/assets/images/15offAd2.png
    - lib/assets/images/Delivery.png
    - lib/assets/images/Activity.png
    - lib/assets/images/Payment.png
    - lib/assets/images/Message.png
    - lib/assets/images/Profile.png
    - lib/assets/images/Wallet.png
    - lib/assets/images/Dashboard.png
    - lib/assets/images/Account.png
    - lib/assets/images/Hombuddynav.png
    - lib/assets/images/Airconditioning.png
    - lib/assets/images/GasRangeHood.png
    - lib/assets/images/WaterHeater.png
    - lib/assets/images/Plumbinglogo.png
    - lib/assets/images/Electricallogo.png
    - lib/assets/images/Carpentrylogo.png
    - lib/assets/images/HombuddyAppbar.png
    - lib/assets/images/BookingLogo.png
    - lib/assets/images/Detailsbook.png
    - lib/assets/images/BookReview.png
    - lib/assets/images/Locationpic.png
    - lib/assets/images/SplashExpert.png
    - lib/assets/images/homblue.png
    - lib/assets/images/MyJobs.png
    - lib/assets/images/1splash.png
    - lib/assets/images/2splash.png
    - lib/assets/images/Button1.png
    - lib/assets/images/Button2.png
    - lib/assets/images/Button3.png
    - lib/assets/images/Button1top.png
    - lib/assets/images/Button2top.png
    - lib/assets/images/Button3top.png
    - lib/assets/images/3splash.png
    - lib/assets/images/Button4.png
    - lib/assets/images/Button4top.png
    - lib/assets/images/Terms.png
    - lib/assets/images/OHNO.png
    - lib/assets/images/BookingSuccess.png
    - lib/assets/images/ACInstall.png
    - lib/assets/images/CleaningService.png
    - lib/assets/images/ACFreon.png
    - lib/assets/images/BasicService.png
    - lib/assets/images/ACPullOut.png
    - lib/assets/images/ACU.png
    - lib/assets/images/PNB.png
    - lib/assets/images/Gcash.png
    - lib/assets/images/Paymaya.png
    - lib/assets/images/bank.png
    - lib/assets/images/bank2.png
    - lib/assets/images/con1.png
    - lib/assets/images/con2.png
    - lib/assets/images/con3.png
    - lib/assets/images/con4.png
    - lib/assets/images/con5.png
    - lib/assets/images/con6.png
    - lib/assets/images/con7.png
    - lib/assets/images/con8.png
    - lib/assets/images/con9.png
    - lib/assets/images/con10.png
    - lib/assets/images/Messagepic.png
    - lib/assets/images/OnTheDay.png
    - lib/assets/images/Offduty.png
    - lib/assets/images/PhotoNotAvailable.png
    - lib/assets/images/Carpentrybg.png
    - lib/assets/images/Plumbingbg.png
    - lib/assets/images/WaterHeaterbg.png
    - lib/assets/images/Electricianbg.png
    - lib/assets/images/GasRangeHoodbg.png
    - lib/assets/images/Settings.png
    - lib/assets/images/HelpCenter.png
    - lib/assets/images/Ohnoo.png
    - lib/assets/images/LoginPin.png
    - lib/assets/images/Moving1.png
    - lib/assets/images/Moving2.png
    - lib/assets/images/Moving3.png
    - lib/assets/images/Moving4.png
    - lib/assets/images/Moving5.png
    - lib/assets/images/Moving6.png
    - lib/assets/images/Moving7.png
    - lib/assets/images/service.png
    - lib/assets/images/facebook.png
    - lib/assets/images/insta.png
    - lib/assets/images/x.png
    - lib/assets/images/tiktok.png
    - lib/assets/images/Challenges.png
    - lib/assets/images/Booking.png
    - lib/assets/images/Payment1.png
    - lib/assets/images/Voucher.png
    - lib/assets/images/Security.png
    - lib/assets/images/App.png
    - lib/assets/images/UserSign.png
    - lib/assets/images/ExpertSign.png
    - lib/assets/images/Ekspertong.png
    - lib/assets/images/WelcomeNote.png
    - lib/assets/images/OneStep.png
    - lib/assets/images/Efficient.png
    - lib/assets/images/Professional.png
    - lib/assets/images/Savvy.png
    - lib/assets/images/Prompt.png
    - lib/assets/images/Reliable.png
    - lib/assets/images/Responsive.png
    - lib/assets/images/Appir.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # flutter:
  # fonts:
    
  #   - family: Lato
  #     fonts:
  #       - asset: fonts/Lato-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
