// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYlE3XLi8MQMh4vHRmr3gN-iFLKkGNonE',
    appId: '1:671635592176:web:3a13ecb12f26dbc1de4335',
    messagingSenderId: '671635592176',
    projectId: 'hom-buddy',
    authDomain: 'hom-buddy.firebaseapp.com',
    databaseURL: 'https://hom-buddy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hom-buddy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfOG9blfeeOhRcfgXqF1ErpAaXVN1GDvY',
    appId: '1:671635592176:android:a2608468ba6da27ade4335',
    messagingSenderId: '671635592176',
    projectId: 'hom-buddy',
    databaseURL: 'https://hom-buddy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hom-buddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rGck12WoShTnQRff86_RVHrsOTt1zKg',
    appId: '1:671635592176:ios:163cd1fc271e6586de4335',
    messagingSenderId: '671635592176',
    projectId: 'hom-buddy',
    databaseURL: 'https://hom-buddy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hom-buddy.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rGck12WoShTnQRff86_RVHrsOTt1zKg',
    appId: '1:671635592176:ios:081b3e0f8e107e4ede4335',
    messagingSenderId: '671635592176',
    projectId: 'hom-buddy',
    databaseURL: 'https://hom-buddy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hom-buddy.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
